### ISSUE TITLE
Use with RGBW pixels

### ISSUE THREAD

**Issue by electronlove** [mendoncaftw/neopixel-rpi-web#1]
Is there any particular trick to getting the flask / python app to work with NeoPixels that use the RGBW ?  I have added a line in the python script to specify LED_STRIP = ws.SK6812_STRIP_RGBW, as well brightness and channel and the appropriate tags in the strip = ... line.

The pixels seem to stay on and not change color at all.  Did I miss something ?

**Comment by mendoncaftw** [comment]
Sorry, haven't touched this for the last 3 years : \. I'm guessing with some extra googling you'll be able to find someone using something similar.

**Comment by electronlove** [comment]
Yes.  I came across PiLights which is a bit more involved, but works.  It is obviously simpler to just drive the NeoPixels by a feather or BLE and use any of the available apps.
